"""2

Revision ID: 1e81a0e8519c
Revises: 7510d8dc70ad
Create Date: 2024-06-20 23:41:29.589493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e81a0e8519c'
down_revision = '7510d8dc70ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amigo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario1_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario2_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['usuario1_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario2_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
