"""Initial migration.

Revision ID: 35465f6f1d5b
Revises: 
Create Date: 2024-06-20 20:10:36.857399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35465f6f1d5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('sp_attack', sa.Integer(), nullable=True),
    sa.Column('sp_defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=100), nullable=True),
    sa.Column('sprite_url', sa.String(length=100), nullable=True),
    sa.Column('imagen_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('imagen_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('imagen_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_habilidad',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('habilidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'habilidad_id')
    )
    op.create_table('pokemon_tipo',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'tipo_id')
    )
    op.create_table('ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_pokemon',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'pokemon_id')
    )
    op.create_table('pokemon_ruta',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['ruta.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'ruta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_ruta')
    op.drop_table('usuario_pokemon')
    op.drop_table('ruta')
    op.drop_table('pokemon_tipo')
    op.drop_table('pokemon_habilidad')
    op.drop_table('usuario')
    op.drop_table('tipo')
    op.drop_table('region')
    op.drop_table('pokemon')
    op.drop_table('habilidad')
    # ### end Alembic commands ###
