INSERT INTO habilidad (id, name, is_hidden) VALUES
(1, 'Stench', false),
(2, 'Drizzle', false),
(3, 'Speed Boost', false),
(4, 'Battle Armor', false),
(5, 'Sturdy', false),
(6, 'Damp', false),
(7, 'Limber', false),
(8, 'Sand Veil', false),
(9, 'Static', false),
(10, 'Volt Absorb', false),
(11, 'Water Absorb', false),
(12, 'Oblivious', false),
(13, 'Cloud Nine', false),
(14, 'Compound Eyes', false),
(15, 'Insomnia', false),
(16, 'Color Change', false),
(17, 'Immunity', false),
(18, 'Flash Fire', false),
(19, 'Shield Dust', false),
(20, 'Own Tempo', false),
(21, 'Suction Cups', false),
(22, 'Intimidate', false),
(23, 'Shadow Tag', false),
(24, 'Rough Skin', false),
(25, 'Wonder Guard', false),
(26, 'Levitate', false),
(27, 'Effect Spore', false),
(28, 'Synchronize', false),
(29, 'Clear Body', false),
(30, 'Natural Cure', false),
(31, 'Lightning Rod', false),
(32, 'Serene Grace', false),
(33, 'Swift Swim', false),
(34, 'Chlorophyll', false),
(35, 'Illuminate', false),
(36, 'Trace', false),
(37, 'Huge Power', false),
(38, 'Poison Point', false),
(39, 'Inner Focus', false),
(40, 'Magma Armor', false),
(41, 'Water Veil', false),
(42, 'Magnet Pull', false),
(43, 'Soundproof', false),
(44, 'Rain Dish', false),
(45, 'Sand Stream', false),
(46, 'Pressure', false),
(47, 'Thick Fat', false),
(48, 'Early Bird', false),
(49, 'Flame Body', false),
(50, 'Run Away', false),
(51, 'Keen Eye', false),
(52, 'Hyper Cutter', false),
(53, 'Pickup', false),
(54, 'Truant', false),
(55, 'Hustle', false),
(56, 'Cute Charm', false),
(57, 'Plus', false),
(58, 'Minus', false),
(59, 'Forecast', false),
(60, 'Sticky Hold', false),
(61, 'Shed Skin', false),
(62, 'Guts', false),
(63, 'Marvel Scale', false),
(64, 'Liquid Ooze', false),
(65, 'Overgrow', false),
(66, 'Blaze', false),
(67, 'Torrent', false),
(68, 'Swarm', false),
(69, 'Rock Head', false),
(70, 'Drought', false),
(71, 'Arena Trap', false),
(72, 'Vital Spirit', false),
(73, 'White Smoke', false),
(74, 'Pure Power', false),
(75, 'Shell Armor', false),
(76, 'Air Lock', false),
(77, 'Tangled Feet', false),
(78, 'Motor Drive', false),
(79, 'Rivalry', false),
(80, 'Steadfast', false),
(81, 'Snow Cloak', false),
(82, 'Gluttony', false),
(83, 'Anger Point', false),
(84, 'Unburden', false),
(85, 'Heatproof', false),
(86, 'Simple', false),
(87, 'Dry Skin', false),
(88, 'Download', false),
(89, 'Iron Fist', false),
(90, 'Poison Heal', false),
(91, 'Adaptability', false),
(92, 'Skill Link', false),
(93, 'Hydration', false),
(94, 'Solar Power', false),
(95, 'Quick Feet', false),
(96, 'Normalize', false),
(97, 'Sniper', false),
(98, 'Magic Guard', false),
(99, 'No Guard', false),
(100, 'Stall', false),
(101, 'Technician', false),
(102, 'Leaf Guard', false),
(103, 'Klutz', false),
(104, 'Mold Breaker', false),
(105, 'Super Luck', false),
(106, 'Aftermath', false),
(107, 'Anticipation', false),
(108, 'Forewarn', false),
(109, 'Unaware', false),
(110, 'Tinted Lens', false),
(111, 'Filter', false),
(112, 'Slow Start', false),
(113, 'Scrappy', false),
(114, 'Storm Drain', false),
(115, 'Ice Body', false),
(116, 'Solid Rock', false),
(117, 'Snow Warning', false),
(118, 'Honey Gather', false),
(119, 'Frisk', false),
(120, 'Reckless', false),
(121, 'Multitype', false),
(122, 'Flower Gift', false),
(123, 'Bad Dreams', false),
(124, 'Pickpocket', false),
(125, 'Sheer Force', false),
(126, 'Contrary', false),
(127, 'Unnerve', false),
(128, 'Defiant', false),
(129, 'Defeatist', false),
(130, 'Cursed Body', false),
(131, 'Healer', false),
(132, 'Friend Guard', false),
(133, 'Weak Armor', false),
(134, 'Heavy Metal', false),
(135, 'Light Metal', false),
(136, 'Multiscale', false),
(137, 'Toxic Boost', false),
(138, 'Flare Boost', false),
(139, 'Harvest', false),
(140, 'Telepathy', false),
(141, 'Moody', false),
(142, 'Overcoat', false),
(143, 'Poison Touch', false),
(144, 'Regenerator', false),
(145, 'Big Pecks', false),
(146, 'Sand Rush', false),
(147, 'Wonder Skin', false),
(148, 'Analytic', false),
(149, 'Illusion', false),
(150, 'Imposter', false),
(151, 'Infiltrator', false),
(152, 'Mummy', false),
(153, 'Moxie', false),
(154, 'Justified', false),
(155, 'Rattled', false),
(156, 'Magic Bounce', false),
(157, 'Sap Sipper', false),
(158, 'Prankster', false),
(159, 'Sand Force', false),
(160, 'Iron Barbs', false),
(161, 'Zen Mode', false),
(162, 'Victory Star', false),
(163, 'Turboblaze', false),
(164, 'Teravolt', false),
(165, 'Aroma Veil', false),
(166, 'Flower Veil', false),
(167, 'Cheek Pouch', false),
(168, 'Protean', false),
(169, 'Fur Coat', false),
(170, 'Magician', false),
(171, 'Bulletproof', false),
(172, 'Competitive', false),
(173, 'Strong Jaw', false),
(174, 'Refrigerate', false),
(175, 'Sweet Veil', false),
(176, 'Stance Change', false),
(177, 'Gale Wings', false),
(178, 'Mega Launcher', false),
(179, 'Grass Pelt', false),
(180, 'Symbiosis', false),
(181, 'Tough Claws', false),
(182, 'Pixilate', false),
(183, 'Gooey', false),
(184, 'Aerilate', false),
(185, 'Parental Bond', false),
(186, 'Dark Aura', false),
(187, 'Fairy Aura', false),
(188, 'Aura Break', false),
(189, 'Primordial Sea', false),
(190, 'Desolate Land', false),
(191, 'Delta Stream', false),
(192, 'Stamina', false),
(193, 'Wimp Out', false),
(194, 'Emergency Exit', false),
(195, 'Water Compaction', false),
(196, 'Merciless', false),
(197, 'Shields Down', false),
(198, 'Stakeout', false),
(199, 'Water Bubble', false),
(200, 'Steelworker', false),
(201, 'Berserk', false),
(202, 'Slush Rush', false),
(203, 'Long Reach', false),
(204, 'Liquid Voice', false),
(205, 'Triage', false),
(206, 'Galvanize', false),
(207, 'Surge Surfer', false),
(208, 'Schooling', false),
(209, 'Disguise', false),
(210, 'Battle Bond', false),
(211, 'Power Construct', false),
(212, 'Corrosion', false),
(213, 'Comatose', false),
(214, 'Queenly Majesty', false),
(215, 'Innards Out', false),
(216, 'Dancer', false),
(217, 'Battery', false),
(218, 'Fluffy', false),
(219, 'Dazzling', false),
(220, 'Soul-Heart', false),
(221, 'Tangling Hair', false),
(222, 'Receiver', false),
(223, 'Power of Alchemy', false),
(224, 'Beast Boost', false),
(225, 'RKS System', false),
(226, 'Electric Surge', false),
(227, 'Psychic Surge', false),
(228, 'Misty Surge', false),
(229, 'Grassy Surge', false),
(230, 'Full Metal Body', false),
(231, 'Shadow Shield', false),
(232, 'Prism Armor', false),
(233, 'Neuroforce', false),
(234, 'Intrepid Sword', false),
(235, 'Dauntless Shield', false),
(236, 'Libero', false),
(237, 'Ball Fetch', false),
(238, 'Cotton Down', false),
(239, 'Propeller Tail', false),
(240, 'Mirror Armor', false),
(241, 'Gulp Missile', false),
(242, 'Stalwart', false),
(243, 'Steam Engine', false),
(244, 'Punk Rock', false),
(245, 'Sand Spit', false),
(246, 'Ice Scales', false),
(247, 'Ripen', false),
(248, 'Ice Face', false),
(249, 'Power Spot', false),
(250, 'Mimicry', false),
(251, 'Screen Cleaner', false),
(252, 'Steely Spirit', false),
(253, 'Perish Body', false),
(254, 'Wandering Spirit', false),
(255, 'Gorilla Tactics', false),
(256, 'Neutralizing Gas', false),
(257, 'Pastel Veil', false),
(258, 'Hunger Switch', false),
(259, 'Quick Draw', false),
(260, 'Unseen Fist', false),
(261, 'Curious Medicine', false),
(262, 'Transistor', false);
